apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: bnt-dev-ip-whitelist
  namespace: bnt-web
spec:
  ipAllowList:
    sourceRange:
      - 75.33.78.238/32
    # ipStrategy:
    #   depth: 1
