apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bnt-web-tls-wildcard
  namespace: bnt-web
spec:
  commonName: "*.bluenimbustech.com"
  secretName: bnt-web-tls-wildcard
  dnsNames:
    - "*.bluenimbustech.com"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
