apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bnt-web-tls-wildcard
  namespace: bnt-web
spec:
  commonName: bluenimbustech.com
  secretName: bnt-web-tls-dev
  dnsNames:
    - 'bluenimbustech.com'
    - 'dev.bluenimbustech.com'
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
