# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: bnt-web-ingress
#   namespace: bnt-web
#   annotations:
#     kubernetes.io/ingress.class: "traefik"
#     cert-manager.io/cluster-issuer: "letsencrypt-staging"
# spec:
#   tls:
#   - hosts:
#     - dev.bluenimbustech.com
#     secretName: dev-bluenimbustech-com-tls
#   rules:
#   - host: dev.bluenimbustech.com
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: bnt-web-service
#             port:
#               number: 80
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bnt-web-ingress
  namespace: bnt-web
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    traefik.ingress.kubernetes.io/use-middlewares: cert-manager
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`dev.bluenimbustech.com`)
      priority: 10
      services:
        - name: bnt-web-service
          port: 80
  tls:
    secretName: dev-bluenimbustech-com-tls
    domains:
    - main: *.bluenimbustech.com
