name: "[BNT - K8s Infra - Deploy ] Deploys out the k8s infra for the Bnt WebApp"

on:
  workflow_dispatch:
    inputs:
        destroy_stack:
            description: 'Set true to tear down the stack, false to deploy it.'
            required: false
            default: 'false'

env:
  OPTIONAL_ARG: ${{ github.event.inputs.optional-arg }}
  TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
  DESTROY_STACK: ${{ github.event.inputs.destroy_stack }}


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      -
        name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      -
        name: Write out required SSH Keys for module
        run: |
          echo "${{ secrets.BNT_HETZNER_K3S_SSHKEY }}" > ./infra/bnt-hetzner-k3s
          echo "${{ secrets.BNT_HETZNER_K3S_SSHKEY_PUB }}" > ./infra/bnt-hetzner-k3s.pub
          chmod 600 ./infra/bnt-hetzner-k3s ./infra/bnt-hetzner-k3s.pub
      -
        name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false
      - 
        name: Tofu Init
        run: |
          tofu -chdir="./infra" init 
      -
        name: Tofu Plan [Deploy]
        if: ${{ env.DESTROY_STACK == 'false' }}
        env:
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
        run: |
          echo "HCLOUD_TOKEN: $TF_VAR_hcloud_token"
          tofu -chdir="./infra" plan -out=otplan
      -
        name: ToFu Plan [Destroy]
        if: ${{ env.DESTROY_STACK == 'true' }}
        run:
          tofu -chdir="./infra" plan -destroy -out=otplan
      -
        name: Tofu Deploy
        if: ${{ env.DESTROY_STACK == 'false' }}
        run: |
          tofu -chdir="./infra" apply otplan
      -
        name: Setup Kubeconfig from Tofu state
        if: ${{ env.DESTROY_STACK == 'false' }}
        run: |
          tofu -chdir="./infra" output kubeconfig > .kubeconfig
      - 
        name: Upload Kubeconfig to AWS Secrets Manager
        if: ${{ env.DESTROY_STACK == 'false' }}
        run: |
          base64 .kubeconfig > encoded_kubeconfig
          aws secretsmanager put-secret-value --secret-id "bnt/ops/web/cluster/kubeconfig" --secret-string file://$(pwd)/encoded_kubeconfig
