name: "[K8s Apps - Deploy] Deploys out the k8s applications to set up our k8s cluster in preperation for the Bnt WebApp"

on:
  workflow_dispatch:
      # workflow_dispatch:
      #   inputs:
      #     optional-arg:
      #       description: 'Set true to do something..'
      #       required: false
      #       default: 'false'
jobs:
  deploy-k8s-apps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      -
        name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      -
        name: Setup Kubectl
        uses: azure/setup-kubectl@v3
      -
        name: Retrieve our Kubernetes Cluster Config from AWS Secrets Manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,bnt/ops/web/cluster/kubeconfig
          parse-json-secrets: true

      -
        name: Setup Kubectl cmd env
        run: |
          echo "KUBECONFIG=$KUBECONFIG" >> $GITHUB_ENV >> ./kubeconfig.yaml
      -
        name: Setup Kubectl cmd env
        run: |
          echo "KUBECTL_CMD=kubectl --kubeconfig=./kubeconfig.yaml" >> $GITHUB_ENV
      - 
        name: Check that our KUBECONFIG is set and working
        run: |
          ${{ env.KUBECTL_CMD }} get nodes
      -
        name: Deploy the GoDaddy Webhook plugin for Cert Manager
        run: |
          export DOMAIN=bluenimbustech.com  
          sed "s/acme.mycompany.com/$DOMAIN/g" ./k8s/core/godaddy-webhook.yaml
          ${{ env.KUBECTL_CMD }} apply --validate=false -f ./k8s/core/godaddy-webhook.yaml
      -
        ## TODO: Refactor this to be provided by a bnt-core Kustomize file
        name: Deploy our GoDaddy Secret for Cert Manager Auth
        run: |
          cat <<EOF > secret.yaml
          apiVersion: v1
          kind: Secret
          metadata:
            name: godaddy-api-key
          type: Opaque
          stringData:
            token: ${{ secrets.GODADDY_API_KEY }}:${{ secrets.GODADDY_API_SECRET }}
          EOF
          ${{ env.KUBECTL_CMD }} apply -f secret.yaml --validate=false --namespace cert-manager
      -
        ## TODO: Add a check to see if the clusterissuer already exists, 
        ## TODO: if it does, then we should skip this step.
        ## TODO: Refactor this to use a bnt-core Kustomize file
        name: Deploy our ClusterIssuer for Cert Manager
        run: |
          ${{ env.KUBECTL_CMD }} apply --validate=false -f ./k8s/core/clusterissuer-staging.yaml
      -
        name: Deploy the Bnt WebApp [DEV] to the k8s cluster
        run: |
          ${{ env.KUBECTL_CMD }} apply --validate=false -k ./k8s/bnt-web/overlays/develop/
